# Generated by Django 5.0 on 2023-12-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('budget', models.CharField(max_length=100)),
            ],
        ),
    ]
