# Generated by Django 5.0 on 2023-12-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_data',
            old_name='movie_name',
            new_name='moviename',
        ),
    ]
