# Generated by Django 5.0 on 2023-12-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0002_rename_movie_name_movie_data_moviename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='budget',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movie_data',
            name='director',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie_data',
            name='moviename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie_data',
            name='release_date',
            field=models.CharField(max_length=50),
        ),
    ]
