# Generated by Django 5.0 on 2023-12-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0003_alter_movie_data_budget_alter_movie_data_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='release_date',
            field=models.DateField(max_length=50),
        ),
    ]
