# Generated by Django 5.0 on 2023-12-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0006_alter_movie_data_release_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_data',
            new_name='MovieData',
        ),
    ]
