# Generated by Django 5.0 on 2023-12-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0007_rename_movie_data_moviedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
