# Generated by Django 5.0 on 2023-12-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0008_alter_moviedata_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
