# Generated by Django 5.0 on 2023-12-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0009_rename_release_date_moviedata_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedata',
            name='release_year',
        ),
        migrations.AddField(
            model_name='moviedata',
            name='release_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
