# Generated by Django 5.0 on 2023-12-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0010_remove_moviedata_release_year_moviedata_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='release_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
